=== DreadPirateRoberts-1000/fimex/share/etc/felt_variables.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/felt_variables.dtd

--><!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE variables SYSTEM "felt_variables.dtd">

    <variables>
    ...
    </variables>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT variables (parameter)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT parameter (attribute)*>
<!ATTLIST parameter
    type CDATA #IMPLIED
    name CDATA #REQUIRED
    id CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT attribute EMPTY>
<!ATTLIST attribute
    type CDATA #REQUIRED
    value CDATA #REQUIRED
    name CDATA #REQUIRED
  >

=== DreadPirateRoberts-1000/fimex/share/etc/felt_variables_hirlam12sf_60h.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE variables SYSTEM "felt_variables.dtd">
<variables>
<parameter id="101,2,1000" name="altitude">
	<attribute name="long_name" value="altitude" type="string" />
	<attribute name="standard_name" value="altitude" type="string" />
	<attribute name="units" value="m" type="string" />
</parameter>
<parameter id="103,2,1000" name="sea_surface_temperature">
	<attribute name="long_name" value="sea_surface_temperature" type="string" />
	<attribute name="standard_name" value="sea_surface_temperature" type="string" />
	<attribute name="scale_factor" value="100" type="float" />
	<attribute name="units" value="K" type="string" />
</parameter>
<parameter id="181,2,1000" name="land_area_fraction">
	<attribute name="long_name" value="land_area_fraction" type="string" />
	<attribute name="metno_name" value="land_area_fraction" type="string" />
	<attribute name="units" value="1" type="string" />
</parameter>
<parameter id="182,2,1000" name="surface_roughness_length">
	<attribute name="long_name" value="surface_roughness_length" type="string" />
	<attribute name="standard_name" value="surface_roughness_length" type="string" />
	<attribute name="metno_info" value="climatology" type="string" />
	<attribute name="units" value="m" type="string" />
</parameter>
<parameter id="183,2,1000" name="soil_temperature" type="short">
	<attribute name="_FillValue" value="-32767" type="short" />
	<attribute name="long_name" value="soil_temperature" type="string" />
	<attribute name="standard_name" value="soil_temperature" type="string" />
	<attribute name="metno_info" value="climatology_deep_soil_temperature" type="string" />
	<attribute name="scale_factor" value="100" type="float" />
	<attribute name="units" value="K" type="string" />
</parameter>
<parameter id="186,2,1000" name="moisture_content_of_soil_layer" type="short">
	<attribute name="_FillValue" value="-32767" type="short" />
	<attribute name="long_name" value="moisture_content_of_soil_layer" type="string" />
	<attribute name="standard_name" value="moisture_content_of_soil_layer" type="string" />
	<attribute name="metno_info" value="climatology_moisture_content_of_deep_soil_layer" type="string" />
	<attribute name="units" value="kg m-2" type="string" />
</parameter>
<parameter id="191,2,1000" name="sea_ice_area_fraction">
	<attribute name="long_name" value="sea_ice_area_fraction" type="string" />
	<attribute name="standard_name" value="sea_ice_area_fraction" type="string" />
	<attribute name="units" value="1" type="string" />
</parameter>

</variables>

=== DreadPirateRoberts-1000/fimex/share/etc/felt_variables_ec_wav.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE variables SYSTEM "felt_variables.dtd">
<variables>
<parameter id="200,3,0" name="significant_wave_height">
    <attribute name="_FillValue" value="-32767" type="short" />
    <attribute name="cell_methods" value="time: point" type="string" />
    <attribute name="long_name" value="sea_surface_wave_significant_height" type="string" />
    <attribute name="standard_name" value="sea_surface_wave_significant_height" type="string" />
    <attribute name="units" value="m" type="string" />
</parameter>
<parameter id="201,3,0" name="peak_wave_period">
    <attribute name="_FillValue" value="-32767" type="short" />
    <attribute name="cell_methods" value="time: point" type="string" />
    <attribute name="long_name" value="sea_surface_wave_peak_period" type="string" />
    <attribute name="units" value="s" type="string" />
</parameter>
<parameter id="202,3,0" name="mean_wave_period">
    <attribute name="_FillValue" value="-32767" type="short" />
    <attribute name="cell_methods" value="time: point" type="string" />
    <attribute name="standard_name" value="sea_surface_wave_mean_period_from_variance_spectral_density_first_frequency_moment" type="string"/>
    <attribute name="units" value="s" type="string" />
</parameter>
<parameter id="204,3,0" name="wave_direction">
    <attribute name="_FillValue" value="-32767" type="short" />
    <attribute name="cell_methods" value="time: point" type="string" />
    <attribute name="long_name" value="sea_surface_wave_to_direction" type="string" />
    <attribute name="standard_name" value="sea_surface_wave_to_direction" type="string" />
    <attribute name="units" value="degree" type="string" />
</parameter>
<parameter id="210,3,0" name="significant_wind_wave_height">
    <attribute name="_FillValue" value="-32767" type="short" />
    <attribute name="cell_methods" value="time: point" type="string" />
    <attribute name="long_name" value="sea_surface_wind_wave_significant_height" type="string" />
    <attribute name="standard_name" value="sea_surface_wind_wave_significant_height" type="string" />
    <attribute name="units" value="m" type="string" />
</parameter>
<parameter id="213,3,0" name="sea_surface_wind_wave_period">
    <attribute name="_FillValue" value="-32767" type="short" />
    <attribute name="cell_methods" value="time: point" type="string" />
    <attribute name="long_name" value="sea_surface_wind_wave_period" type="string" />
    <attribute name="standard_name" value="sea_surface_wind_wave_period" type="string" />
    <attribute name="units" value="s" type="string" />
</parameter>
<parameter id="214,3,0" name="sea_surface_wind_wave_to_direction">
    <attribute name="_FillValue" value="-32767" type="short" />
    <attribute name="cell_methods" value="time: point" type="string" />
    <attribute name="long_name" value="sea_surface_wind_wave_to_direction" type="string" />
    <attribute name="standard_name" value="sea_surface_wind_wave_to_direction" type="string" />
    <attribute name="units" value="degree" type="string" />
</parameter>
<parameter id="220,3,0" name="significant_swell_wave_height">
    <attribute name="_FillValue" value="-32767" type="short" />
    <attribute name="cell_methods" value="time: point" type="string" />
    <attribute name="long_name" value="sea_surface_swell_wave_significant_height" type="string" />
    <attribute name="standard_name" value="sea_surface_swell_wave_significant_height" type="string" />
    <attribute name="units" value="m" type="string" />
</parameter>
<parameter id="223,3,0" name="sea_surface_swell_wave_period">
    <attribute name="_FillValue" value="-32767" type="short" />
    <attribute name="cell_methods" value="time: point" type="string" />
    <attribute name="long_name" value="sea_surface_swell_wave_period" type="string" />
    <attribute name="standard_name" value="sea_surface_swell_wave_period" type="string" />
    <attribute name="units" value="s" type="string" />
</parameter>
<parameter id="224,3,0" name="sea_surface_swell_wave_to_direction">
    <attribute name="_FillValue" value="-32767" type="short" />
    <attribute name="cell_methods" value="time: point" type="string" />
    <attribute name="long_name" value="sea_surface_swell_wave_to_direction" type="string" />
    <attribute name="standard_name" value="sea_surface_swell_wave_to_direction" type="string" />
    <attribute name="units" value="degree" type="string" />
</parameter>
</variables>

=== DreadPirateRoberts-1000/fimex/share/etc/felt_variables_hirlam12sf_3h.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE variables SYSTEM "felt_variables.dtd">
<variables>
<!--  I dont use components in model-layer 59/60 (see hirlam12ml) -->
<parameter id="8,2,1000" name="air_pressure">
	<attribute name="_FillValue" value="-32767" type="short" />
	<attribute name="cell_methods" value="time: point" type="string" />
	<attribute name="long_name" value="air_pressure_at_sea_level" type="string" />
	<attribute name="standard_name" value="air_pressure_at_sea_level" type="string" />
	<attribute name="scale_factor" value="10" type="float" />
	<attribute name="units" value="hPa" type="string" />
</parameter>
<parameter id="19" name="lwe_thickness_of_large_scale_precipitation_amount" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="long_name" value="lwe_thickness_of_large_scale_precipitation_amount" type="string" />
	<attribute name="standard_name" value="lwe_thickness_of_large_scale_precipitation_amount" type="string" />
	<attribute name="units" value="mm" type="string" />
</parameter>
<parameter id="20" name="lwe_thickness_of_convective_precipitation_amount" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="long_name" value="lwe_thickness_of_convective_precipitation_amount" type="string" />
	<attribute name="standard_name" value="lwe_thickness_of_convective_precipitation_amount" type="string" />
	<attribute name="units" value="mm" type="string" />
</parameter>
<parameter id="21" name="tendency_of_surface_air_pressure" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="long_name" value="tendency_of_surface_air_pressure" type="string" />
	<attribute name="standard_name" value="tendency_of_surface_air_pressure" type="string" />
	<attribute name="units" value="Pa s-1" type="string" />
</parameter>
<parameter id="22,2,1000" name="cloud_liquid_water_content_of_atmosphere_layer" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="long_name" value="cloud_liquid_water_content_of_atmosphere_layer" type="string" />
	<attribute name="standard_name" value="cloud_liquid_water_content_of_atmosphere_layer" type="string" />
	<attribute name="metno_name" value="qliq" type="string" />
	<attribute name="units" value="kg m-2" type="string" />
</parameter>
<parameter id="29,2,1000" name="soil_temperature" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="cell_methods" value="time: point" type="string" />
	<attribute name="long_name" value="soil_temperature" type="string" />
	<attribute name="standard_name" value="soil_temperature" type="string" />
	<attribute name="units" value="K" type="string" />
</parameter>
<parameter id="30,2,1000" name="air_temperature" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="cell_methods" value="time: point" type="string" />
	<attribute name="long_name" value="air_temperature" type="string" />
	<attribute name="standard_name" value="air_temperature" type="string" />
	<attribute name="units" value="K" type="string" />
</parameter>
<parameter id="35,2,1000" name="surface_downwelling_shortwave_flux_in_air" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="long_name" value="surface_downwelling_shortwave_flux_in_air" type="string" />
	<attribute name="standard_name" value="surface_downwelling_shortwave_flux_in_air" type="string" />
	<attribute name="units" value="W/m2" type="string" />
	<attribute name="cell_method" value="time: mean" type="string" />
	<attribute name="scaling_factor" value=".277777" type="double" /> <!-- 1000/3600 - check with hirlam folk about accumulation time!!! -->
</parameter>
<!-- change in scale_factor -->
<parameter id="36,2,1000" name="surface_upward_sensible_heat_flux" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="long_name" value="surface_upward_sensible_heat_flux" type="string" />
	<attribute name="standard_name" value="surface_upward_sensible_heat_flux" type="string" />
	<attribute name="units" value="W/m2" type="string" />
	<attribute name="cell_method" value="time: mean" type="string" />
	<attribute name="scaling_factor" value=".277777" type="double" /> <!-- 1000/3600 - check with hirlam folk about accumulation time!!! -->
</parameter>
<parameter id="37,2,1000" name="surface_upward_latent_heat_flux" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="long_name" value="surface_upward_latent_heat_flux" type="string" />
	<attribute name="standard_name" value="surface_upward_latent_heat_flux" type="string" />
	<attribute name="units" value="W/m2" type="string" />
	<attribute name="cell_method" value="time: mean" type="string" />
	<attribute name="scaling_factor" value=".277777" type="double" /> <!-- 1000/3600 - check with hirlam folk about accumulation time!!! -->
</parameter>
<parameter id="63,2,1000" name="lwe_thickness_of_snowfall_amount" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="long_name" value="lwe_thickness_of_snowfall_amount" type="string" />
	<attribute name="standard_name" value="lwe_thickness_of_snowfall_amount" type="string" />
	<attribute name="units" value="mm" type="string" />
</parameter>
<parameter id="64,2,1000" name="lwe_thickness_of_large_scale_snowfall_amount" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="long_name" value="lwe_thickness_of_large_scale_snowfall_amount" type="string" />
	<attribute name="metno_name" value="lwe_thickness_of_large_scale_snowfall_amount" type="string" />
	<attribute name="units" value="mm" type="string" />
</parameter>
<parameter id="65,2,1000" name="lwe_thickness_of_convective_snowfall_amount" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="long_name" value="lwe_thickness_of_convective_snowfall_amount" type="string" />
	<attribute name="standard_name" value="lwe_thickness_of_convective_snowfall_amount" type="string" />
	<attribute name="units" value="mm" type="string" />
</parameter>
<parameter id="66,2,1000" name="lwe_thickness_of_surface_snow_amount">
	<attribute name="long_name" value="lwe_thickness_of_surface_snow_amount" type="string" />
	<attribute name="standard_name" value="lwe_thickness_of_surface_snow_amount" type="string" />
	<attribute name="units" value="m" type="string" />
</parameter>
<parameter id="83,2,1000" name="surface_roughness_length" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="long_name" value="surface_roughness_length" type="string" />
	<attribute name="standard_name" value="surface_roughness_length" type="string" />
	<attribute name="units" value="m" type="string" />
</parameter>
<parameter id="85,2,1000" name="soil_moisture_content">
	<attribute name="long_name" value="soil_moisture_content" type="string" />
	<attribute name="standard_name" value="soil_moisture_content" type="string" />
	<attribute name="units" value="kg/m2" type="string" />
</parameter>
<parameter id="86,2,1000" name="moisture_content_of_soil_layer" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="long_name" value="moisture_content_of_soil_layer" type="string" />
	<attribute name="standard_name" value="moisture_content_of_soil_layer" type="string" />
	<attribute name="metno_info" value="deep_soil" type="string"/>
	<attribute name="units" value="kg/m2" type="string" />
</parameter>
<parameter id="87,2,1000" name="surface_longwave_radiation" type="float" >
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="long_name" value="surface_longwave_radiation" type="string" />
	<attribute name="metno_name" value="surface_longwave_radiation" type="string" />
	<attribute name="units" value="kW m-2 s-1" type="string" />
</parameter>
<parameter id="175,2,1000" name="surface_albedo">
	<attribute name="long_name" value="surface_albedo" type="string" />
	<attribute name="standard_name" value="surface_albedo" type="string" />
	<attribute name="scale_factor" value="0.01" type="float" />
	<attribute name="units" value="1" type="string" />
</parameter>
</variables>

=== DreadPirateRoberts-1000/fimex/share/etc/felt_variables_hirlam12sf_1h.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE variables SYSTEM "felt_variables.dtd">
<variables>
<!--  I dont use components in model-layer 59/60 (see hirlam12ml) -->
<parameter id="17,2,1000" name="precipitation_amount" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="long_name" value="precipitation_amount" type="string" />
	<attribute name="standard_name" value="precipitation_amount" type="string" />
	<attribute name="units" value="kg/m2" type="string" />
</parameter>
<parameter id="25,2,1000" name="cloud_area_fraction">
	<attribute name="scale_factor" value="0.01" type="float" />
	<attribute name="_FillValue" value="-32767" type="short" />
	<attribute name="cell_methods" value="time: point" type="string" />
	<attribute name="long_name" value="cloud_area_fraction" type="string" />
	<attribute name="standard_name" value="cloud_area_fraction" type="string" />
	<attribute name="units" value="1" type="string" />
</parameter>
<parameter id="31,2,1000" name="air_temperature" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="cell_methods" value="time: point height: 2m" type="string" />
	<attribute name="long_name" value="air_temperature_2m" type="string" />
	<attribute name="standard_name" value="air_temperature" type="string" />
	<attribute name="units" value="K" type="string" />
</parameter>
<parameter id="32,2,1000" name="relative_humidity">
	<attribute name="_FillValue" value="-32767" type="short" />
	<attribute name="scale_factor" value="0.01" type="float" />
	<attribute name="cell_methods" value="time: point height: 2m" type="string" />
	<attribute name="long_name" value="relative_humidity" type="string" />
	<attribute name="standard_name" value="relative_humidity" type="string" />
	<attribute name="units" value="1" type="string" />
</parameter>
<!--  currently not distributing vector data due to missing support in fimex
<parameter id="33,2,1000" name="x_wind">
	<attribute name="_FillValue" value="-32767" type="short" />
	<attribute name="cell_methods" value="time: point height: 10m" type="string" />
	<attribute name="long_name" value="x_wind" type="string" />
	<attribute name="standard_name" value="x_wind" type="string" />
	<attribute name="height" value="10m" type="string" />
	<attribute name="units" value="m s-1" type="string" />
</parameter>
<parameter id="34,2,1000" name="y_wind">
	<attribute name="_FillValue" value="-32767" type="short" />
	<attribute name="cell_methods" value="time: point height: 10m" type="string" />
	<attribute name="long_name" value="y_wind" type="string" />
	<attribute name="standard_name" value="y_wind" type="string" />
	<attribute name="height" value="10m" type="string" />
	<attribute name="units" value="m s-1" type="string" />
</parameter>
-->
<parameter id="39" name="cloud_area_fraction_in_atmosphere_layer">
	<attribute name="long_name" value="cloud_area_fraction_in_atmosphere_layer" type="string" />
	<attribute name="standard_name" value="cloud_area_fraction_in_atmosphere_layer" type="string" />
	<attribute name="scale_factor" value="0.01" type="float" />
	<attribute name="units" value="1" type="string" />
</parameter>
<parameter id="58,2,1000" name="sea_level_pressure">
	<attribute name="scale_factor" value="100." type="float" />
	<attribute name="_FillValue" value="-32767" type="short" />
	<attribute name="cell_methods" value="time: point" type="string" />
	<attribute name="long_name" value="air_pressure_at_sea_level" type="string" />
	<attribute name="standard_name" value="air_pressure_at_sea_level" type="string" />
	<attribute name="units" value="Pa" type="string" />
</parameter>
<parameter id="131,2,1000" name="surface_temperature_where_land">
	<attribute name="long_name" value="surface_temperature_where_land" type="string" />
	<attribute name="standard_name" value="surface_temperature_2m_where_land" type="string" />
	<attribute name="metno_info" value="height: 2m" type="string"/>
	<attribute name="units" value="K" type="string" />
</parameter>
</variables>

=== DreadPirateRoberts-1000/fimex/share/etc/felt_variables_hirlam12pl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE variables SYSTEM "felt_variables.dtd">
<variables>
<parameter id="1" name="geopotential_height" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36" type="float" />
	<attribute name="long_name" value="geopotential_height" type="string" />
	<attribute name="standard_name" value="geopotential_height" type="string" />
	<attribute name="units" value="m" type="string" />
</parameter>
<parameter id="2" name="x_wind" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36" type="float" />
	<attribute name="long_name" value="x_wind" type="string" />
	<attribute name="standard_name" value="x_wind" type="string" />
	<attribute name="units" value="m/s" type="string" />
	<spatial_vector direction="x,longitude" counterpart="y_wind" />
</parameter>
<parameter id="3" name="y_wind" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36" type="float" />
	<attribute name="long_name" value="y_wind" type="string" />
	<attribute name="standard_name" value="y_wind" type="string" />
	<attribute name="units" value="m/s" type="string" />
	<spatial_vector direction="y,latitude" counterpart="x_wind" />
</parameter>
<parameter id="10" name="relative_humidity" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36" type="float" />
	<attribute name="scale_factor" value="0.01" type="float" />
	<attribute name="long_name" value="relative_humidity" type="string" />
	<attribute name="standard_name" value="relative_humidity" type="string" />
	<attribute name="units" value="1" type="string" />
</parameter>
<parameter id="13" name="omega" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36" type="float" />
	<attribute name="long_name" value="lagrangian_tendency_of_air_pressure" type="string" />
	<attribute name="standard_name_alias" value="vertical_air_velocity_expressed_as_tendency_of_pressure" type="string" />	
	<attribute name="standard_name" value="lagrangian_tendency_of_air_pressure" type="string" />
	<attribute name="units" value="1000 hPa/s" type="string" />
</parameter>
<parameter id="18" name="air_potential_temperature" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36" type="float" />
	<attribute name="long_name" value="air_potential_temperature" type="string" />
	<attribute name="standard_name" value="air_potential_temperature" type="string" />
	<attribute name="units" value="K" type="string" />
</parameter>
</variables>

=== DreadPirateRoberts-1000/fimex/share/etc/felt_variables_hirlam12ml.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE variables SYSTEM "felt_variables.dtd">
<variables>
<parameter id="2" name="x_wind">
	<attribute name="_FillValue" value="-32767" type="short" />
	<attribute name="long_name" value="x_wind" type="string" />
	<attribute name="standard_name" value="x_wind" type="string" />
	<attribute name="units" value="m/s" type="string" />
	<spatial_vector direction="x,longitude" counterpart="y_wind" />
</parameter>
<parameter id="3" name="y_wind">
	<attribute name="_FillValue" value="-32767" type="short" />
	<attribute name="long_name" value="y_wind" type="string" />
	<attribute name="standard_name" value="y_wind" type="string" />
	<attribute name="units" value="m/s" type="string" />
	<spatial_vector direction="y,latitude" counterpart="x_wind" />
</parameter>
<parameter id="9" name="specific_humidity" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="scale_factor" value="0.01" type="float" />
	<attribute name="long_name" value="specific_humidity" type="string" />
	<attribute name="standard_name" value="specific_humidity" type="string" />
	<attribute name="units" value="1" type="string" />
</parameter>
<parameter id="10" name="relative_humidity">
	<attribute name="scale_factor" value="0.01" type="float" />
	<attribute name="_FillValue" value="-32767" type="short" />
	<attribute name="long_name" value="relative_humidity" type="string" />
	<attribute name="standard_name" value="relative_humidity" type="string" />
	<attribute name="units" value="1" type="string" />
</parameter>
<parameter id="11" name="sigma_dot" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="long_name" value="sigma_dot" type="string" />
	<attribute name="metno_name" value="sigma_dot" type="string" />
	<attribute name="units" value="1" type="string" />
</parameter>
<parameter id="13" name="omega" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="long_name" value="relative_humidity" type="string" />
	<attribute name="standard_name_alias" value="vertical_air_velocity_expressed_as_tendency_of_pressure" type="string" />	
	<attribute name="standard_name" value="lagrangian_tendency_of_air_pressure" type="string" />
	<attribute name="units" value="1000 hPa/s" type="string" />
</parameter>
<parameter id="18" name="air_potential_temperature" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="long_name" value="air_potential_temperature" type="string" />
	<attribute name="standard_name" value="air_potential_temperature" type="string" />
	<attribute name="units" value="K" type="string" />
</parameter>
<parameter id="22" name="cloud_liquid_water_content_of_atmosphere_layer" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="long_name" value="cloud_liquid_water_content_of_atmosphere_layer" type="string" />
	<attribute name="standard_name" value="cloud_liquid_water_content_of_atmosphere_layer" type="string" />
	<attribute name="metno_name" value="qliq" type="string" />
	<attribute name="units" value="kg m-2" type="string" />
</parameter>
<parameter id="23" name="precipitation_amount" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="long_name" value="precipitation_amount" type="string" />
	<attribute name="standard_name" value="precipitation_amount" type="string" />
	<attribute name="units" value="kg/m2" type="string" />
</parameter>
</variables>
