=== DreadPirateRoberts-1000/fimex/share/etc/felt_variables.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/felt_variables.dtd

--><!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE variables SYSTEM "felt_variables.dtd">

    <variables>
    ...
    </variables>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT variables (parameter)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT parameter (attribute)*>
<!ATTLIST parameter
    type CDATA #IMPLIED
    name CDATA #REQUIRED
    id CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT attribute EMPTY>
<!ATTLIST attribute
    type CDATA #REQUIRED
    value CDATA #REQUIRED
    name CDATA #REQUIRED
  >

=== DreadPirateRoberts-1000/fimex/share/etc/felt_variables_ec_mad_0_25.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE variables SYSTEM "felt_variables.dtd">
<variables>
<parameter id="25" name="cloud_area_fraction">
	<attribute name="long_name" value="cloud_area_fraction" type="string" />
	<attribute name="standard_name" value="cloud_area_fraction" type="string" />
	<attribute name="scale_factor" value="0.01" type="float" />
	<attribute name="units" value="1" type="string" />
</parameter>
<parameter id="30,2,1000" name="air_temperature" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="cell_methods" value="time: point" type="string" />
	<attribute name="long_name" value="air_temperature" type="string" />
	<attribute name="standard_name" value="air_temperature" type="string" />
	<attribute name="units" value="K" type="string" />
</parameter>
<parameter id="31,2,1000" name="air_temperature_2m" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="cell_methods" value="time: point" type="string" />
	<attribute name="long_name" value="air_temperature_2m" type="string" />
	<attribute name="standard_name" value="air_temperature" type="string" />
	<attribute name="units" value="K" type="string" />
</parameter>
<parameter id="32,2,1000" name="relative_humidity_2m" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="scale_factor" value="0.01" type="float" />
	<attribute name="long_name" value="relative_humidity_2m" type="string" />
	<attribute name="standard_name" value="relative_humidity" type="string" />
	<attribute name="units" value="1" type="string" />
</parameter>
<parameter id="33,2,1000" name="x_wind_10m" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="long_name" value="x_wind_10m" type="string" />
	<attribute name="standard_name" value="x_wind" type="string" />
	<attribute name="units" value="m/s" type="string" />
	<spatial_vector direction="x,longitude" counterpart="y_wind" />
</parameter>
<parameter id="34,2,1000" name="y_wind_10m" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="long_name" value="y_wind_10m" type="string" />
	<attribute name="standard_name" value="y_wind" type="string" />
	<attribute name="units" value="m/s" type="string" />
	<spatial_vector direction="y,latitude" counterpart="x_wind" />
</parameter>
<parameter id="58,2,1000" name="sea_level_pressure">
	<attribute name="scale_factor" value="100." type="float" />
	<attribute name="_FillValue" value="-32767" type="short" />
	<attribute name="cell_methods" value="time: point" type="string" />
	<attribute name="long_name" value="air_pressure_at_sea_level" type="string" />
	<attribute name="standard_name" value="air_pressure_at_sea_level" type="string" />
	<attribute name="units" value="Pa" type="string" />
</parameter>
<parameter id="66,2,1000" name="lwe_thickness_of_surface_snow_amount">
	<attribute name="long_name" value="lwe_thickness_of_surface_snow_amount" type="string" />
	<attribute name="standard_name" value="lwe_thickness_of_surface_snow_amount" type="string" />
	<attribute name="units" value="m" type="string" />
</parameter>
<parameter id="103,2,1000" name="sea_surface_temperature">
	<attribute name="long_name" value="sea_surface_temperature" type="string" />
	<attribute name="standard_name" value="sea_surface_temperature" type="string" />
	<attribute name="scale_factor" value="100" type="float" />
	<attribute name="units" value="K" type="string" />
</parameter>

<parameter id="39" name="cloud_area_fraction_in_atmosphere_layer">
	<attribute name="long_name" value="cloud_area_fraction_in_atmosphere_layer" type="string" />
	<attribute name="standard_name" value="cloud_area_fraction_in_atmosphere_layer" type="string" />
	<attribute name="scale_factor" value="0.01" type="float" />
	<attribute name="units" value="1" type="string" />
</parameter>
<!-- parameter id="42" -->

<parameter id="17,2,1000" name="precipitation_amount" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="long_name" value="precipitation_amount" type="string" />
	<attribute name="standard_name" value="precipitation_amount" type="string" />
	<attribute name="units" value="kg/m2" type="string" />
</parameter>
<parameter id="19,2,1000" name="lwe_thickness_of_large_scale_precipitation_amount" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="long_name" value="lwe_thickness_of_large_scale_precipitation_amount" type="string" />
	<attribute name="standard_name" value="lwe_thickness_of_large_scale_precipitation_amount" type="string" />
	<attribute name="units" value="mm" type="string" />
</parameter>
<parameter id="20,2,1000" name="lwe_thickness_of_convective_precipitation_amount" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="long_name" value="lwe_thickness_of_convective_precipitation_amount" type="string" />
	<attribute name="standard_name" value="lwe_thickness_of_convective_precipitation_amount" type="string" />
	<attribute name="units" value="mm" type="string" />
</parameter>
<parameter id="121,2,1000" name="max_air_temperature_2m" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="long_name" value="max_air_temperature_2m" type="string" />
	<attribute name="cell_methods" value="time: maximum" type="string"/>
	<attribute name="description" value="maximum over the last 6h" type="string" /> 
	<attribute name="standard_name" value="air_temperature" type="string" />
	<attribute name="units" value="K" type="string" />
</parameter>
<parameter id="122,2,1000" name="min_air_temperature_2m" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="long_name" value="min_air_temperature_2m" type="string" />
	<attribute name="cell_methods" value="time: minimum" type="string"/>
	<attribute name="description" value="minimum over the last 6h" type="string" /> 
	<attribute name="standard_name" value="air_temperature" type="string" />
	<attribute name="units" value="K" type="string" />
</parameter>
<parameter id="126,2,1000" name="max_wind_speed_of_gust_10m" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36f" type="float" />
	<attribute name="long_name" value="max_wind_speed_of_gust_10m" type="string" />
	<attribute name="cell_methods" value="time: maximum" type="string"/>
	<attribute name="description" value="maximum over the last 6h" type="string" /> 
	<attribute name="standard_name" value="wind_speed_of_gust" type="string" />
	<attribute name="units" value="K" type="string" />
</parameter>

</variables>

=== DreadPirateRoberts-1000/fimex/share/etc/felt_variables_ec_mad_0_5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE variables SYSTEM "felt_variables.dtd">
<variables>
<parameter id="1" name="geopotential_height" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36" type="float" />
	<attribute name="long_name" value="geopotential_height" type="string" />
	<attribute name="standard_name" value="geopotential_height" type="string" />
	<attribute name="units" value="m" type="string" />
</parameter>
<parameter id="2" name="x_wind" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36" type="float" />
	<attribute name="long_name" value="x_wind" type="string" />
	<attribute name="standard_name" value="x_wind" type="string" />
	<attribute name="units" value="m/s" type="string" />
	<spatial_vector direction="x,longitude" counterpart="y_wind" />
</parameter>
<parameter id="3" name="y_wind" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36" type="float" />
	<attribute name="long_name" value="y_wind" type="string" />
	<attribute name="standard_name" value="y_wind" type="string" />
	<attribute name="units" value="m/s" type="string" />
	<spatial_vector direction="y,latitude" counterpart="x_wind" />
</parameter>
<parameter id="4,1" name="air_temperature" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36" type="float" />
	<attribute name="long_name" value="air_temperature" type="string" />
	<attribute name="standard_name" value="air_temperature" type="string" />
	<attribute name="units" value="K" type="string" />
</parameter>
<parameter id="10" name="relative_humidity" type="float">
	<attribute name="_FillValue" value="9.9692099683868690e+36" type="float" />
	<attribute name="scale_factor" value="0.01" type="float" />
	<attribute name="long_name" value="relative_humidity" type="string" />
	<attribute name="standard_name" value="relative_humidity" type="string" />
	<attribute name="units" value="1" type="string" />
</parameter>


</variables>
