=== DreadPirateRoberts-1000/fimex/share/etc/metgm_config.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- WARNING -->
<!-- Draft XSD schema that will be used by both:        -->
<!--         MetGmCDMReader and MetGmCDMWriter          -->
<!-- Expect further changes in near future              -->
<!-- August 2011, Aleksandar Babic, aleksandarb@met.no  -->


<xs:simpleType name="DataType">
    <xs:restriction base="xs:token">
        <xs:enumeration value="float"/>
        <xs:enumeration value="short"/>
        <xs:enumeration value="string"/>
     </xs:restriction>
</xs:simpleType>

<xs:complexType name="attribute_type">
    <xs:attribute name="name"  type="xs:string" use="required"/>
    <xs:attribute name="value" type="xs:string" use="required"/>
    <xs:attribute name="type"  type="DataType"  use="optional" default="string"/>
</xs:complexType>

<xs:complexType name="attribute_list">
    <xs:sequence>
        <xs:element name="attribute" type="attribute_type" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="mapping_type">
    <xs:sequence>
        <xs:element name="attribute" type="attribute_type" minOccurs="2" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="mapping_with_name_attribute_type">
    <xs:complexContent>
        <xs:extension base="mapping_type">
            <xs:attribute name="name"  type="xs:string" use="required"/>
        </xs:extension>
    </xs:complexContent>
</xs:complexType>

<xs:complexType name="variable_mapping_list">
    <xs:sequence>
        <xs:element name="variable" type="mapping_with_name_attribute_type" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="metgm_mapping_list">
    <xs:sequence>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="variable"        type="mapping_with_name_attribute_type" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="metgm_parameter" type="mapping_with_name_attribute_type" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="metgm_config_type">
    <xs:all>
        <!--xs:choice minOccurs="0" maxOccurs="unbounded"-->
            <xs:element name="metgm_meta_data" type="attribute_list"         minOccurs="0"/>
            <xs:element name="reader"          type="variable_mapping_list"  minOccurs="0"/>
            <xs:element name="writer"          type="metgm_mapping_list"     minOccurs="0"/>
        <!--xs:choice-->
    </xs:all>
</xs:complexType>

<xs:element name="metgm_config" type="metgm_config_type"/>

</xs:schema>

=== DreadPirateRoberts-1000/fimex/share/etc/cdmMetGmWriterConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<metgm_config xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="metgm_config.xsd">

<meta_data>
    <attribute name="metgm_analysis_date_time" value="2005-02-04T00:00:00" type="string" />
    <attribute name="metgm_start_date_time" value="2005-02-04T06:00:00" type="string" />
    <attribute name="metgm_version" value="STANAG_6022_Edition_1" type="string" />
    <attribute name="metgm_data_type" value="2 - Numerical weather prediction" type="string" />
    <attribute name="metgm_production_nation" value="FRA" type="string" />
</meta_data>


<writer>

    <metgm_parameter name="altitude">
        <attribute name="standard_name" value="altitude" type="string" />
        <attribute name="metgm_p_id"    value="0"        type="short" />
    </metgm_parameter>

    <metgm_parameter name="humidity">
        <attribute name="standard_name" value="relative_humidity" type="string" />
        <attribute name="metgm_p_id"    value="6"                 type="short" />
    </metgm_parameter>

    <metgm_parameter name="temperature">
        <attribute name="standard_name" value="air_temperature" type="string" />
        <attribute name="metgm_p_id"    value="5"                         type="short" />
    </metgm_parameter>

    <metgm_parameter name="y_wind">
        <attribute name="standard_name" value="y_wind" type="string" />
        <attribute name="metgm_p_id"    value="3"              type="short" />
    </metgm_parameter>

    <metgm_parameter name="x_wind">
        <attribute name="standard_name" value="x_wind" type="string" />
        <attribute name="metgm_p_id"    value="2"      type="short" />
    </metgm_parameter>

    <metgm_parameter name="z_wind">
        <attribute name="standard_name" value="upward_air_velocity" type="string" />
        <attribute name="metgm_p_id"    value="2"      type="short" />
    </metgm_parameter>


    <variable name="geopotential_height" >
        <attribute name="standard_name" value="geopotential_height" type="string" />
        <attribute name="metgm_p_id"    value="7"                   type="short"  />
        <attribute name="units"         value="m"                   type="string"/>
    </variable>

    <metgm_parameter name="air_pressure" >
        <attribute name="standard_name" value="air_pressure" type="string" />
        <attribute name="metgm_p_id"    value="7"        type="short" />
        <attribute name="units"         value="hPa"                   type="string"/>
    </metgm_parameter>

</writer>

</metgm_config>
